# Walk Forward: A Realistic Approach to Backtesting

## Load the data

In [1]:
import pandas as pd

df = pd.read_excel('data/Microsoft_LinkedIn_Processed.xlsx', parse_dates=['Date'], index_col=0)
df = df.drop(columns='change_tomorrow_direction')
df = df.dropna()

## Walk Forward Validation

### How `TimeSeriesSplit` works

In [2]:
from sklearn.model_selection import TimeSeriesSplit

In [3]:
ts = TimeSeriesSplit(test_size=200)

In [4]:
splits = ts.split(X=df)

In [5]:
split1= next(splits)

In [6]:
split1

(array([   0,    1,    2, ..., 1067, 1068, 1069], shape=(1070,)),
 array([1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 1079, 1080,
        1081, 1082, 1083, 1084, 1085, 1086, 1087, 1088, 1089, 1090, 1091,
        1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099, 1100, 1101, 1102,
        1103, 1104, 1105, 1106, 1107, 1108, 1109, 1110, 1111, 1112, 1113,
        1114, 1115, 1116, 1117, 1118, 1119, 1120, 1121, 1122, 1123, 1124,
        1125, 1126, 1127, 1128, 1129, 1130, 1131, 1132, 1133, 1134, 1135,
        1136, 1137, 1138, 1139, 1140, 1141, 1142, 1143, 1144, 1145, 1146,
        1147, 1148, 1149, 1150, 1151, 1152, 1153, 1154, 1155, 1156, 1157,
        1158, 1159, 1160, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1168,
        1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179,
        1180, 1181, 1182, 1183, 1184, 1185, 1186, 1187, 1188, 1189, 1190,
        1191, 1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199, 1200, 1201,
        1202, 1203, 1204, 1205, 1206, 1207, 12

In [7]:
split2= next(splits)

In [8]:
split2

(array([   0,    1,    2, ..., 1267, 1268, 1269], shape=(1270,)),
 array([1270, 1271, 1272, 1273, 1274, 1275, 1276, 1277, 1278, 1279, 1280,
        1281, 1282, 1283, 1284, 1285, 1286, 1287, 1288, 1289, 1290, 1291,
        1292, 1293, 1294, 1295, 1296, 1297, 1298, 1299, 1300, 1301, 1302,
        1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310, 1311, 1312, 1313,
        1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324,
        1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335,
        1336, 1337, 1338, 1339, 1340, 1341, 1342, 1343, 1344, 1345, 1346,
        1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357,
        1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368,
        1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1379,
        1380, 1381, 1382, 1383, 1384, 1385, 1386, 1387, 1388, 1389, 1390,
        1391, 1392, 1393, 1394, 1395, 1396, 1397, 1398, 1399, 1400, 1401,
        1402, 1403, 1404, 1405, 1406, 1407, 14

In [9]:
list_df_train = []
list_df_test = []

for index_train, index_test in ts.split(df):
    list_df_train.append(df.iloc[index_train])
    list_df_test.append(df.iloc[index_test])

In [10]:
list_df_train[0]

Close        High         Low        Open    Volume  \
Date                                                                   
2016-12-08   55.181118   55.696664   55.027361   55.443412  21220800   
2016-12-09   56.049408   56.067498   55.289661   55.334883  27349400   
2016-12-12   56.230297   56.347878   55.823293   55.913737  20198100   
2016-12-13   56.962921   57.360883   56.293622   56.528781  35718900   
2016-12-14   56.691578   57.388013   56.555907   56.981005  30352700   
...                ...         ...         ...         ...       ...   
2021-03-05  223.935318  225.550048  218.965424  221.924153  41872800   
2021-03-08  219.864670  225.646761  219.613280  223.712950  35267400   
2021-03-09  226.043182  227.590237  224.003011  225.172973  33080500   
2021-03-10  224.728165  229.156593  224.360736  229.156593  29746800   
2021-03-11  229.282333  231.254814  226.555652  227.184150  29907600   

            change_tomorrow  
Date                         
2016-12-08         1.549151  
2016-12-09         0.321693  
2016-12-12         1.286142  
2016-12-13        -0.478631  
2016-12-14        -0.159796  
...                     ...  
2021-03-05        -1.851434  
2021-03-08         2.733333  
2021-03-09        -0.585159  
2021-03-10         1.986271  
2021-03-11        -0.585362  

[1070 rows x 6 columns]

In [11]:
list_df_test[0]

Close        High         Low        Open    Volume  \
Date                                                                   
2021-03-12  227.948013  228.015704  225.511407  226.265592  22653700   
2021-03-15  227.039108  227.406537  224.138391  227.184153  26034900   
2021-03-16  229.843155  232.115374  228.131728  228.460472  28092200   
2021-03-17  229.195312  230.655349  225.511404  228.334767  29562100   
2021-03-18  223.084442  226.439605  222.707350  224.863545  34833000   
...                ...         ...         ...         ...       ...   
2021-12-17  314.982880  316.072407  308.611249  312.142408  47750300   
2021-12-20  311.198822  314.010112  308.922544  311.334994  28326500   
2021-12-21  318.377960  318.805981  311.091891  314.486879  24740600   
2021-12-22  324.126984  324.525793  316.879835  319.360387  24831500   
2021-12-23  325.576385  327.230106  323.669765  323.689209  19617800   

            change_tomorrow  
Date                         
2021-03-12        -0.400330  
2021-03-15         1.219983  
2021-03-16        -0.282660  
2021-03-17        -2.739263  
2021-03-18        -0.160619  
...                     ...  
2021-12-17        -1.215961  
2021-12-20         2.254911  
2021-12-21         1.773695  
2021-12-22         0.445180  
2021-12-23         2.266045  

[200 rows x 6 columns]

In [12]:
list_df_train[1]

Close        High         Low        Open    Volume  \
Date                                                                   
2016-12-08   55.181118   55.696664   55.027361   55.443412  21220800   
2016-12-09   56.049408   56.067498   55.289661   55.334883  27349400   
2016-12-12   56.230297   56.347878   55.823293   55.913737  20198100   
2016-12-13   56.962921   57.360883   56.293622   56.528781  35718900   
2016-12-14   56.691578   57.388013   56.555907   56.981005  30352700   
...                ...         ...         ...         ...       ...   
2021-12-17  314.982880  316.072407  308.611249  312.142408  47750300   
2021-12-20  311.198822  314.010112  308.922544  311.334994  28326500   
2021-12-21  318.377960  318.805981  311.091891  314.486879  24740600   
2021-12-22  324.126984  324.525793  316.879835  319.360387  24831500   
2021-12-23  325.576385  327.230106  323.669765  323.689209  19617800   

            change_tomorrow  
Date                         
2016-12-08         1.549151  
2016-12-09         0.321693  
2016-12-12         1.286142  
2016-12-13        -0.478631  
2016-12-14        -0.159796  
...                     ...  
2021-12-17        -1.215961  
2021-12-20         2.254911  
2021-12-21         1.773695  
2021-12-22         0.445180  
2021-12-23         2.266045  

[1270 rows x 6 columns]

In [13]:
list_df_test[1]

Close        High         Low        Open    Volume  \
Date                                                                   
2021-12-27  333.125153  333.154335  326.296287  326.325469  19947000   
2021-12-28  331.957794  334.448083  331.053125  333.806051  15661500   
2021-12-29  332.638763  334.924750  330.430556  332.006439  15042000   
2021-12-30  330.080292  333.786543  329.593907  332.599762  15994500   
2021-12-31  327.162018  330.119217  326.704815  329.292387  18000800   
...                ...         ...         ...         ...       ...   
2022-10-05  243.998138  245.349337  239.004606  240.855153  20347100   
2022-10-06  241.638443  245.114342  240.943272  242.754646  20239900   
2022-10-07  229.350433  236.282646  228.302762  235.871400  37769600   
2022-10-10  224.464569  229.663724  221.997168  228.185250  29743600   
2022-10-11  220.704758  224.278561  219.431891  222.868617  30474000   

            change_tomorrow  
Date                         
2021-12-27        -0.351659  
2021-12-28         0.204717  
2021-12-29        -0.775106  
2021-12-30        -0.891997  
2021-12-31        -0.469017  
...                     ...  
2022-10-05        -0.976540  
2022-10-06        -5.357744  
2022-10-07        -2.176675  
2022-10-10        -1.703548  
2022-10-11         0.150594  

[200 rows x 6 columns]

## Machine Learning Model

### Separate the data

1. Target: which variable do you want to predict?
2. Explanatory: which variables will you use to calculate the prediction?

In [14]:
y = df.change_tomorrow
X = df[['Open','High','Low','Close','Volume']]

In [15]:
list_df_train = []
list_df_test = []

for index_train, index_test in ts.split(df):
    X_train, y_train = X.iloc[index_train], y.iloc[index_train]
    X_test, y_test = X.iloc[index_test], y.iloc[index_test]


### Simulate one computation of the ML model

- Compute the model
- Calculate predictions on the test set
- Evaluate how good the model is

In [16]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error

model_dt = DecisionTreeRegressor(max_depth=15, random_state=42)
model_dt.fit(X_train, y_train)

y_pred = model_dt.predict(X_test)
error_mse = mean_squared_error(y_test, y_pred)
error_mse

2.7961011635940998

### Add the procedure inside the for loop

In [17]:
model_dt = DecisionTreeRegressor(max_depth=15, random_state=42)

error_mse_list = []

for index_train, index_test in ts.split(df):
    X_train, y_train = X.iloc[index_train], y.iloc[index_train]
    X_test, y_test = X.iloc[index_test], y.iloc[index_test]
    
    model_dt.fit(X_train, y_train)
    
    y_pred = model_dt.predict(X_test)
    error_mse = mean_squared_error(y_test, y_pred)
    
    error_mse_list.append(error_mse)

In [18]:
error_mse_list

[2.7197884453366123,
 7.132894968718692,
 7.377379074067753,
 6.303621801386867,
 2.7961011635940998]

In [19]:
import  numpy as np

In [20]:
np.mean(error_mse_list)

np.float64(5.265957090620804)

## Anchored Walk Forward evaluation in backtesting

### Create a new strategy

In [21]:
from backtesting import Backtest, Strategy

/home/codespace/.python/current/lib/python3.12/site-packages/backtesting/_plotting.py:54: UserWarning: Jupyter Notebook detected. Setting Bokeh output to notebook. This may not work in Jupyter clients without JavaScript support (e.g. PyCharm, Spyder IDE). Reset with `backtesting.set_bokeh_output(notebook=False)`.
  warnings.warn('Jupyter Notebook detected. '


Loading BokehJS ...

In [22]:
df

Close        High         Low        Open    Volume  \
Date                                                                   
2016-12-08   55.181118   55.696664   55.027361   55.443412  21220800   
2016-12-09   56.049408   56.067498   55.289661   55.334883  27349400   
2016-12-12   56.230297   56.347878   55.823293   55.913737  20198100   
2016-12-13   56.962921   57.360883   56.293622   56.528781  35718900   
2016-12-14   56.691578   57.388013   56.555907   56.981005  30352700   
...                ...         ...         ...         ...       ...   
2025-02-27  392.529999  405.739990  392.170013  401.269989  21127400   
2025-02-28  396.989990  397.630005  386.570007  392.660004  32845700   
2025-03-03  388.489990  398.820007  386.160004  398.820007  23007700   
2025-03-04  388.609985  392.579987  381.000000  383.399994  29342900   
2025-03-05  401.019989  401.670013  388.809998  389.339996  23412000   

            change_tomorrow  
Date                         
2016-12-08         1.549151  
2016-12-09         0.321693  
2016-12-12         1.286142  
2016-12-13        -0.478631  
2016-12-14        -0.159796  
...                     ...  
2025-02-27         1.123452  
2025-02-28        -2.187959  
2025-03-03         0.030878  
2025-03-04         3.094610  
2025-03-05        -1.322278  

[2070 rows x 6 columns]

In [23]:
bt = Backtest(df, Strategy, cash=10000, commission=.002, exclusive_orders=True)

In [24]:
class Regression(Strategy):
    limit_buy = 1
    limit_sell = -5
    
    n_train = 600
    coef_retrain = 200
    
    def init(self):
        self.model = DecisionTreeRegressor(max_depth=15, random_state=42)
        self.already_bought = False
        
        X_train = self.data.df.iloc[:self.n_train, :-1]
        y_train = self.data.df.iloc[:self.n_train, -1]
        
        self.model.fit(X=X_train, y=y_train)

    def next(self):
        explanatory_today = self.data.df.iloc[[-1], :-1]
        forecast_tomorrow = self.model.predict(explanatory_today)[0]
        
        if forecast_tomorrow > self.limit_buy and self.already_bought == False:
            self.buy()
            self.already_bought = True
        elif forecast_tomorrow < self.limit_sell and self.already_bought == True:
            self.sell()
            self.already_bought = False
        else:
            pass

In [25]:
class WalkForwardAnchored(Regression):
    def next(self):
        
        # we don't take any action and move on to the following day
        if len(self.data) < self.n_train:
            return
        
        # we retrain the model each 200 days
        if len(self.data) % self.coef_retrain == 0:
            X_train = self.data.df.iloc[:, :-1]
            y_train = self.data.df.iloc[:, -1]

            self.model.fit(X_train, y_train)

            super().next()
            
        else:
            
            super().next()

In [26]:
from backtesting import Backtest
bt = Backtest(df, WalkForwardAnchored, cash=10000, commission=.002, exclusive_orders=True)

In [27]:
import multiprocessing as mp
mp.set_start_method('fork')

In [28]:
!pip install sambo


[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python3 -m pip install --upgrade pip


In [29]:
stats_skopt, heatmap, optimize_result = bt.optimize(
    limit_buy = range(0, 6), limit_sell = range(-6, 0),
    maximize='Return [%]',
    max_tries=500,
    random_state=42,
    return_heatmap=True,
    return_optimization=True,
    method='skopt'
    )

dff = heatmap.reset_index()
dff = dff.sort_values('Return [%]', ascending=False)
dff

/tmp/ipykernel_15419/310560374.py:1: DeprecationWarning: `Backtest.optimize(method="skopt")` is deprecated. Use `method="sambo"`.
  stats_skopt, heatmap, optimize_result = bt.optimize(


limit_buy  limit_sell  Return [%]
15          3          -6  177.900958
9           2          -6  107.321959
3           1          -6  101.968509
0           0          -6   83.306296
16          3          -5   62.049684
22          4          -5   58.366708
21          4          -6   58.366708
23          4          -4   58.366708
26          5          -6   58.366708
28          5          -4   58.366708
27          5          -5   58.366708
17          3          -4   53.178947
4           1          -5   40.563755
5           1          -4    9.024558
1           0          -4   -0.883394
6           1          -3  -22.853008
10          2          -5  -25.802258
11          2          -4  -34.806683
25          4          -2  -37.421913
30          5          -2  -37.421913
24          4          -3  -37.421913
29          5          -3  -37.421913
7           1          -2  -39.850560
2           0          -2  -40.775159
18          3          -3  -49.988324
13          2          -2  -50.597647
8           1          -1  -61.636901
12          2          -3  -65.686110
19          3          -2  -69.952805
14          2          -1  -74.026516
20          3          -1  -77.911757

## Unanchored Walk Forward

### Import the strategy and perform the backtest

In [30]:
%load_ext autoreload
%autoreload 2

In [31]:
import strategies

In [32]:
strategies.WalkForwardUnanchored

strategies.WalkForwardUnanchored

In [ ]:
bt_unanchored = Backtest(df, strategies.WalkForwardUnanchored, cash=10000, commission=.002, exclusive_orders=True)

stats_skopt, heatmap, optimize_result = bt_unanchored.optimize(
    limit_buy = range(0, 6), limit_sell = range(-6, 0),
    maximize='Return [%]',
    max_tries=500,
    random_state=42,
    return_heatmap=True,
    return_optimization=True,
    method='skopt'
    )

dff = heatmap.reset_index()
dff = dff.sort_values('Return [%]', ascending=False)
dff

/tmp/ipykernel_15419/1717563861.py:3: DeprecationWarning: `Backtest.optimize(method="skopt")` is deprecated. Use `method="sambo"`.
  stats_skopt, heatmap, optimize_result = bt_unanchored.optimize(


### Interpret the strategies' performance

In [ ]:
bt.plot(filename='reports_backtesting/walk_forward_anchored.html')

In [ ]:
bt_unanchored.plot(filename='reports_backtesting/walk_forward_unanchored.html')